### ISSUE TITLE
infer the payload based on examples

### ISSUE THREAD

**Issue by mbiuki** [microsoft/restler-fuzzer#153]
By testing and from user guide documentation (/blob/main/docs/user-guide/Examples.md), I find that RESTler compiler does not use examples in the swagger to construct a valid string for a number of properties. For example for `lastDoneBefore' in the swagger file we have:

```
- in: query
  name: lastDoneBefore
  description: Last done service before date and time or duration.
  examples:
    FullUtcTimestamp:
      value: 2008-01-23T12:05:01.700Z
    DateOnly:
      value: 2008-01-23T00:06:00.000Z
    Duration:
      value: '-P1DT8H5M10S'
      summary: >-
        1 day 8 hours 5 minutes and 10 seconds ago, value is
        case-sensitive
    DaysOnly:
      value: P3D
      summary: 3 day from now
    HoursOnly:
      value: '-PT8H'
      summary: 8 hours ago
    MinutesOnly:
      value: '-PT32M'
      summary: 32minutes ago
    SecondsOnly:
      value: PT100S
      summary: 100 seconds from now
  required: false
  schema:
    type: string
```

RESTler cannot interpret the examples in the schema above to construct a valid string for lastDoneBefore.
This probably is the main cause for most of our 40x errors. 

```
2021-02-05 04:20:29.127: Sending: 'GET /url/api/work?pageFromKey=fuzzstring&pageSize=0&pageTotal=true&sort=["fuzzstring"]&healthStatus=["good"]&type=["machine"]&tamperProtectionEnabled=true&lockdownStatus=["creatingWhitelist"]&lastDoneBefore=fuzzstring&lastDoneAfter=fuzzstring&ids=["fuzzstring"]&fields=["fuzzstring"]&view=basic HTTP/1.1\r\nAccept: */*\r\nHost: api-rg01.xyz.org\r\nContent-Type: application/json\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate, br\r\nX-KLM-ID: <...>\r\n_OMITTED_AUTH_TOKEN_\r\nContent-Length: 0\r\nUser-Agent: restler/7.2.0\r\n\r\n'

2021-02-05 04:20:29.411: Received: 'HTTP/1.1 400 \r\nDate: Tue, 05 Feb 2021 04:20:29 GMT\r\nContent-Type: application/json\r\nContent-Length: 231\r\nConnection: keep-alive\r\nX-Correlation-ID: <...>\r\nX-Request-ID: <...>\r\n\r\n{\n    "error": "illegalArgument",\n    "correlationId": "<...>",\n    "requestId": "<...>",\n    "createdAt": "2021-02-05T04:20:29.262Z",\n    "message": "Invalid request"\n}
```

 Are there going to be any updates to RESTler's compiler for this matter?

Otherwise, do I have to add the property to fix custom strings using the "restler_custom_payload" field in dict.json? Is there any better solution, for example, adding to examples.json file?

**Comment by mbiuki** [comment]
In addition to the above, I also find that the header in parameters from the swagger is not compiled into the grammar.json. I would have to do it manually. For example:

```
  /api/item:
    get:
      visib-cat: test
      summary: Query something
      description: List something in the directory.
      docs-review: true
      operationId: listSomething
      tags:
        - Directory Management
      parameters:
        - name: App-ID
          in: header
          description: uuid of the App using this API.
          required: true
          schema:
            type: string
            format: uuid
        - in: ...
```

Our header requests require that we have **App-ID**. So I have to edit the grammar.json file:

```
"headers": [
        [
          "Accept",
          "*/*"
        ],
        [
          "Host",
          "api-R1.something.com"
        ],
        [
          "Content-Type",
          "application/json"
        ],
        [
          "Connection",
          "keep-alive"
        ],
        [
          "Accept-Encoding",
          "gzip, deflate, br"
        ],
        [
          "App-ID",
          "<uuid placeholder for app-id>"
        ]
      ]
```

**Comment by marina-p** [comment]
Hello @mbiuki,

We will investigate this issue, as RESTler should support getting example values for the query parameter.  However, note that currently RESTler only supports using the first example in the 'Test' phase.  My suggestion would be to use ```restler_custom_payload``` to list all of the values of the named query parameter if only some of them are expected to be valid, and this will also ensure they are all tried during fuzzing with sufficient parameter combinations.  

A reason to use examples.json instead of ```restler_custom_payload``` is if you need to specify the entire set of parameters, for example if this query parameter must have a specific value to match another path/body parameter.  This often comes up with enum values that indicate supported features in the rest of the request payload.

Please let us know if you run into any issues using restler_custom_payload or examples.json for your use case.

Thanks,

Marina

**Comment by mbiuki** [comment]
### ONE

I am not sure how I can do this exactly. Are there any samples to show us how this could be done?
From https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Examples.md I see this peice:

```
{
    "Examples": {
        "First example": {
            "$ref":  "./examples/first.json"
        },
        "Second example": {
            "$ref":  "./examples/second.json"
        }        
    }
}
```

So I create a file called examples.json in my Compile directory and copy the above? Or, does the compiler do this for me?

I tried running the following command from the Compile folder and I do not see any examples sub-directory created in the compilation folder. Please advise. Here is the command I ran from the "/myproject/Compile" directory:

`restler.exe compile config.json`

My config.json looks like this:

```
{
  "SwaggerSpecFilePath": [
    "/myproject/consolidated.yaml"
  ],
  "GrammarOutputDirectoryPath": "/myproject/Compile",
  "GrammarInputFilePath": "/myproject/Compile/grammar.json",
  "CustomDictionaryFilePath": "/myproject/Compile/dict.json",
  "EngineSettingsFilePath":  "/myproject/Compile/restler_user_settings.json",
  "IncludeOptionalParameters": true,
  "UseBodyExamples": true,
  "UseQueryExamples": true,
  "DiscoverExamples": true,
  "ExamplesDirectory": "/myproject/Compile/Example",
  "DataFuzzing": true,
  "ReadOnlyFuzz": false,
  "ResolveQueryDependencies": true,
  "ResolveBodyDependencies": true,
  "UseRefreshableToken": true,
  "AllowGetProducers": false
}
```
As can be followed, DiscoverExamples is set to true, and ExamplesDirectory path has been added, however, I do not see a new directory created for examples?


### TWO

I find that our server accepts arrays without square brackets and strings without quotes. The reason is that we are having style values of the following in our open API file: 
```
explode: false
style: form
```
these two allow for csv format syntax for arrays without square brackets and without quotations for strings. See: https://swagger.io/docs/specification/serialization/

- Is there an option in the compiler section of RESTler that we can turn-off square brackets in arrays and quotations around strings in the body parameters?
- Could the examples file help us to mitigate the above body construction matter? At the moment, I have to manually go into grammar.py and edit the file. And it works only for GET requests only. PUT requests, I have to inspect again to see what is wrong. Is there a possibility that we can mitigate this matter with examples? If so, is it possible to provide a sample?

For example, this is a query that I have succeeded w/o any quotation around strings and brackets around array:

`https://sample.com/test/site?groupCluster=KSLTJWY5&from=2021-01-26&to=2021-01-26&sort=api&product=microsoft&category=azure&severity=low&ids=1111111-1111-1111-1111-1111111111&fields=category,product,severity&pageSize=1000&pageFromKey=1&pageTotal=True`

If I put brackets around the fields body parameter, which is an array, or if I put quotes around any of the strings, I get 400 errors.

In the OpenAPI, as an example, for fields parameter I have:

```
        - name: fields
          description: The fields to return the requested.
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
```

I have 34/56 queries to have

```
          style: form
          explode: false
```
 constructs in my OpenAPI specification file.

**Comment by InLineR495** [comment]
> ### ONE
> I am not sure how I can do this exactly. Are there any samples to show us how this could be done?
> From https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Examples.md I see this peice:
> 
> ```
> {
>     "Examples": {
>         "First example": {
>             "$ref":  "./examples/first.json"
>         },
>         "Second example": {
>             "$ref":  "./examples/second.json"
>         }        
>     }
> }
> ```
> 
> So I create a file called examples.json in my Compile directory and copy the above? Or, does the compiler do this for me?
> 
> I tried running the following command from the Compile folder and I do not see any examples sub-directory created in the compilation folder. Please advise. Here is the command I ran from the "/myproject/Compile" directory:
> 
> `restler.exe compile config.json`
> 
> My config.json looks like this:
> 
> ```
> {
>   "SwaggerSpecFilePath": [
>     "/myproject/consolidated.yaml"
>   ],
>   "GrammarOutputDirectoryPath": "/myproject/Compile",
>   "GrammarInputFilePath": "/myproject/Compile/grammar.json",
>   "CustomDictionaryFilePath": "/myproject/Compile/dict.json",
>   "EngineSettingsFilePath":  "/myproject/Compile/restler_user_settings.json",
>   "IncludeOptionalParameters": true,
>   "UseBodyExamples": true,
>   "UseQueryExamples": true,
>   "DiscoverExamples": true,
>   "ExamplesDirectory": "/myproject/Compile/Example",
>   "DataFuzzing": true,
>   "ReadOnlyFuzz": false,
>   "ResolveQueryDependencies": true,
>   "ResolveBodyDependencies": true,
>   "UseRefreshableToken": true,
>   "AllowGetProducers": false
> }
> ```
> 
> As can be followed, DiscoverExamples is set to true, and ExamplesDirectory path has been added, however, I do not see a new directory created for examples?
> 
> ### TWO
> I find that our server accepts arrays without square brackets and strings without quotes. The reason is that we are having style values of the following in our open API file:
> 
> ```
> explode: false
> style: form
> ```
> 
> these two allow for csv format syntax for arrays without square brackets and without quotations for strings. See: https://swagger.io/docs/specification/serialization/
> 
> * Is there an option in the compiler section of RESTler that we can turn-off square brackets in arrays and quotations around strings in the body parameters?
> * Could the examples file help us to mitigate the above body construction matter? At the moment, I have to manually go into grammar.py and edit the file. And it works only for GET requests only. PUT requests, I have to inspect again to see what is wrong. Is there a possibility that we can mitigate this matter with examples? If so, is it possible to provide a sample?
> 
> For example, this is a query that I have succeeded w/o any quotation around strings and brackets around array:
> 
> `https://sample.com/test/site?groupCluster=KSLTJWY5&from=2021-01-26&to=2021-01-26&sort=api&product=microsoft&category=azure&severity=low&ids=1111111-1111-1111-1111-1111111111&fields=category,product,severity&pageSize=1000&pageFromKey=1&pageTotal=True`
> 
> If I put brackets around the fields body parameter, which is an array, or if I put quotes around any of the strings, I get 400 errors.
> 
> In the OpenAPI, as an example, for fields parameter I have:
> 
> ```
>         - name: fields
>           description: The fields to return the requested.
>           in: query
>           style: form
>           explode: false
>           schema:
>             type: array
>             items:
>               type: string
> ```
> 
> I have 34/56 queries to have
> 
> ```
>           style: form
>           explode: false
> ```
> 
> constructs in my OpenAPI specification file.

Hi! Did you find answers for ONE and TWO? I have same questions but no answers

**Comment by marina-p** [comment]
Hi @mbiuki,

Re: One - examples currently need to be linked from the specification file, in the same place as parameters and responses properties, and you do not need to specify examples.json.  For example:
```
                "examples": {
                    "First example": {
                        "$ref": "./examples/first.json"
                    }
                },
                "responses": {
                    "200": {
```

This limitation will be fixed soon, and the new behavior will be that you specify your examples in examples.json and use it as an input (to avoid having to modify the spec if it does not originally have examples).  This is tracked in issue #10.

Re: Two - RESTler currently does not support these and will need to be extended to take these parameters into account.  Unfortunately, there is no current workaround. This will be tracked by this issue.

Thanks,

Marina

**Comment by marina-p** [comment]
Hello @mbiuki @InLineR495, 

I pushed a branch with better support for arrays that addresses the above issue TWO: 
mp/175_part2

If you have a few minutes, could you please try it to make sure it works for your service?  

Thanks!

Marina

**Comment by mbiuki** [comment]
Thank you @marina-p, I can see your origin/mp/175_part2 branch, please allow me by the end of today to check this. I believe this change, will take care of style values, `explode:false; style:form`, so we should not expect to see square brackets for arrays and quotations for strings in grammar.py, right?

**Comment by mbiuki** [comment]
Hi @marina-p, I just did a test and confirm that on branch `mp/175_part2`, the Restler engine compiles properties with `explode:false; style:form` as w/o quotes for strings and square brackets for arrays as specified in the query parameter standard (https://swagger.io/docs/specification/serialization/). This is reflected in the grammar.py and so no manual fix is needed. Thank you.

**Comment by mbiuki** [comment]
On a separate note, it could also be nice to have the above merge with the below header fix too: 
```
      parameters:
        - name: X-KLM-ID
          in: header
          description: KLM ID.
          required: true
          schema:
            type: string
            format: uuid
```

To include `X-KLM-ID` as a header parameter with a dedicated value from `dict.json`:
```
"restler_custom_payload_header": {
    "X-KLM-ID": [
      "d4dd94e8-dcb2-4e8c-927d-b254e5e73260"
    ],
    "dataRegion": [
      "ca01"
    ]
  },
```

OR,

```
"restler_custom_payload": 
{
    ...
    "X-KLM-ID": [
      "d4dd94e8-dcb2-4e8c-927d-b257e5e73261"
    ],
    ...
}
```
And have the above to compile in grammar.py. At the moment, I manually add the header UUID param to the `grammar.json` and should re-compile to have the effect appear in `grammar.py`.
Thanks!

**Comment by marina-p** [comment]
@mbiuki Great, thanks for confirming.

The header fix will be checked in soon, in a separate change (tracked by #156).

**Comment by marina-p** [comment]
@mbiuki The header fix is now merged

**Comment by marina-p** [comment]
Hi @mbiuki, if you have a chance, could you please try out the change in the above PR (branch mp/examples) and confirm this fixes your datetime issue?  (This still generates a fuzzable_string when the format is not specified, but the default value will be the example).

**Comment by mbiuki** [comment]
Hi @marina-p, I checked this by going to `mp/examples` branch and building Restler. I did not see changes effective. Here is what I did. 

1. I ran `Restler compile --api_spec openapi.yaml`
the openapi.yaml includes the following constructs:
```
        - in: query
          name: lastSeenBefore
          description: >-
            Find last seen before the given date and time.
          x-ijk-docs-review: true
          examples:
            FullUtcTimestamp:
              value: 2019-09-23T12:02:01.700Z
            DateOnly:
              value: 2019-09-23T00:00:00.000Z
            Duration:
              value: '-P3DT4H5M0S'
              summary: >-
                3 days 4 hours 5 minutes and 0 seconds ago, value is
                case-sensitive
            DaysOnly:
              value: P1D
              summary: one day from now
            HoursOnly:
              value: '-PT2H'
              summary: 2 hours ago
            MinutesOnly:
              value: '-PT20M'
              summary: 20 minutes ago
            SecondsOnly:
              value: PT200S
              summary: 200 seconds from now
          required: false
          schema:
            type: string
        - in: query
          name: lastSeenAfter
          description: >-
            Find last seen after the given date and time.
          x-ijk-docs-review: true
          examples:
            FullUtcTimestamp:
              value: 2019-09-23T12:02:01.700Z
            DateOnly:
              value: 2019-09-23T00:00:00.000Z
            Duration:
              value: PT4H500S
              summary: '4 hours and 500 seconds from now, value is case-sensitive'
            DaysOnly:
              value: '-P1D'
              summary: one day ago
            HoursOnly:
              value: PT2H
              summary: 2 hours from now
            MinutesOnly:
              value: PT20M
              summary: 20 minutes from now
            SecondsOnly:
              value: '-PT200S'
              summary: 200 seconds ago
          required: false
          schema:
            type: string
```
However, when I ran the compiler, I still see the following in `grammar.py`:
   ```
 primitives.restler_static_string("lastSeenBefore="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("lastSeenAfter="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
```
I also wonder if we are to correct dates to use a valid dateTime string, the following in the `dict.json` could also be ISO compliant:
```
  "restler_fuzzable_datetime": [
    "6/25/2019 12:00:00 AM"
  ],
```

**Comment by marina-p** [comment]
@mbiuki Thanks for testing this out.  I believe I fixed the issue you were seeing, can you please try the mp/examples branch again?

Regarding dict.json - could you please clarify?   You can modify this value after the default is generated to ones that work for you - that is the purpose of the dictionary.

**Comment by mbiuki** [comment]
> @mbiuki Thanks for testing this out. I believe I fixed the issue you were seeing, can you please try the mp/examples branch again?

Sure, I can re-try to see if it works. I will give you an update by next week.

> Regarding dict.json - could you please clarify? You can modify this value after the default is generated to ones that work for you - that is the purpose of the dictionary.

Sounds good. I recall, when I changed it to ISO, grammar.py reverted the result. I can double-check this as well.

**Comment by marina-p** [comment]
@mbiuki Thanks, sounds good.  

Quick clarification regarding your comment "grammar.py reverted the result":

grammar.py values are currently default values that are overridden by the dictionary.  For example, if the grammar has ```restler_fuzzable_string("fuzzstring",...)```, but your dictionary has ```"restler_fuzzable_string": ["a"]``` , only "a" will be used.  This actually does not interact well with the new feature introduced by this issue - I may need to make another small update to the engine to make sure those values are used.  For now - when you test this latest update in 'Test' mode, please remove the ```"restler_fuzzable_string"``` section from the dictionary.

Please let me know if anything above is unclear.

**Comment by mbiuki** [comment]
Ok, so for testing this ticket, I am going to remove `restler_fuzzable_string` from `dict.json` and see how things roll out - although I was playing with `restler_fuzzable_datetime` to see why ISO format is not showing up in grammar.py after compilation.
```
 "restler_fuzzable_datetime": [
    "2020-03-09T16:54:13Z"    <-------Using ISO format should reflect in grammar.py after we compile.
  ],
```
Eventually, we want to reflect whatever is present in `dict.json` to `grammar.py`. If we have `restler_fuzzable_datetime` in ISO format, we should see `dateTime` in ISO format across grammar.py when we compile. Another option is to keep compilation as is, but add an ISO binary option. If ISO flag is true, then generate `dateTime` in ISO format, otherwise, keep as is.

**Comment by mbiuki** [comment]
Hi @marina-p, I still see the same as tested before. I removed the fuzzstring from dict.json. But, still see 
```
    primitives.restler_static_string("from="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
```
in `grammar.py`.
```
This is how my dict.json looks like:
{
  "restler_fuzzable_string_unquoted": [],
  "restler_fuzzable_datetime": [
    "2020-03-09T16:54:13Z"
  ],
  "restler_fuzzable_datetime_unquoted": [],
  "restler_fuzzable_uuid4": [
    "903bcc44-30cf-4ea7-968a-d9d0da7c072f"
  ],
  "restler_fuzzable_uuid4_unquoted": [],
  "restler_fuzzable_int": [
    "0",
    "1"
  ],
  "restler_fuzzable_number": [
    "0.1",
    "1.2"
  ],
  "restler_fuzzable_bool": [
    "true"
  ],
  "restler_fuzzable_object": [
    "{}"
  ],
  "restler_custom_payload": {},
  "restler_custom_payload_unquoted": {},
  "restler_custom_payload_uuid4_suffix": {},
  "restler_custom_payload_header": {
    "X-KLM-ID": [
      "d4dd94e8-dcb2-4e8c-927d-b254e5e73260"
    ]
  }
}
```
And this is my `openapi.yaml`:
 ```
 - in: query
          name: from
          description: on or after this time.
          x-ijk-docs-review: true
          schema:
            type: string
            format: datetime
```

**Comment by marina-p** [comment]
Hi @mbiuki,

Can you please confirm that when you test your other example specification, where there is an array of "examples" for the datetime, one of the examples now appears in grammar.py, instead of 'fuzzstring'?  This one does not have any examples, and we'll investigate separately why 'format:datetime' isn't taken into account for this one.

**Comment by mbiuki** [comment]
Hi @marina-p, I see the same effect with the ones that even have examples. See `lastSeenBefore` and `lastSeenAfter` below.
Here is a snippet:
```
        - in: query
          name: lastSeenBefore
          description: >-
            Find last seen before.
          x-ijk-docs-review: true
          examples:
            FullUtcTimestamp:
              value: 2019-09-23T12:02:01.700Z
            DateOnly:
              value: 2019-09-23T00:00:00.000Z
            Duration:
              value: '-P3DT4H5M0S'
              summary: >-
                3 days 4 hours 5 minutes and 0 seconds ago, value is
                case-sensitive
            DaysOnly:
              value: P1D
              summary: one day from now
            HoursOnly:
              value: '-PT2H'
              summary: 2 hours ago
            MinutesOnly:
              value: '-PT20M'
              summary: 20 minutes ago
            SecondsOnly:
              value: PT200S
              summary: 200 seconds from now
          required: false
          schema:
            type: string
        - in: query
          name: lastSeenAfter
          description: >-
            Find endpoints that were last seen after.
          x-ijk-docs-review: true
          examples:
            FullUtcTimestamp:
              value: 2019-09-23T12:02:01.700Z
            DateOnly:
              value: 2019-09-23T00:00:00.000Z
            Duration:
              value: PT4H500S
              summary: '4 hours and 500 seconds from now, value is case-sensitive'
            DaysOnly:
              value: '-P1D'
              summary: one day ago
            HoursOnly:
              value: PT2H
              summary: 2 hours from now
            MinutesOnly:
              value: PT20M
              summary: 20 minutes from now
            SecondsOnly:
              value: '-PT200S'
              summary: 200 seconds ago
          required: false
          schema:
            type: string
        - in: query
          name: ids
          description: Find with the specified IDs.
          x-ijk-docs-review: true
          style: form
          explode: false
          required: false
          schema:
            type: array
            items:
              type: string
```
and the resulting `grammar.py`:
```
    primitives.restler_static_string("&"),
    primitives.restler_static_string("lastSeenBefore="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("lastSeenAfter="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
```

**Comment by mbiuki** [comment]
Hi @marina-p,

Thanks for your message. I have reported my experience of the fix a couple of times above. If you believe this issue is fixed as intended please close this ticket.

Thanks

Mehdi

**Comment by marina-p** [comment]
Hellow @mbiuki,

As you mentioned in #348, do you still see an issue where 'fuzzstring' is appearing instead of your specification examples?  Or was your issue caused by the fact that RESTler was adding those additional dates (as discussed in #348)?  We should re-open this issue if it is the former, but if the date format of the additional dates is the issue, the resolution to #348 will address it.

Thanks,

Marina

**Comment by mbiuki** [comment]
Thanks for your reply. At our front, we would have to modify the string `datetime` to include dash. It would also be useful to add a case to support `datetime'.
